sudo: required
services: 
  - docker
  
before_install:
  - docker build -t kothamasu/docker-complexreact -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kothamasu/docker-complexreact npm run test

after_success:
  - docker build -t kothamasu/multi-client ./client
  - docker build -t kothamasu/multi-nginx ./nginx
  - docker build -t kothamasu/multi-server ./server
  - docker build -t kothamasu/multi-worker ./worker
  # login to dockerhub
  - echo "$DOCKERPWD" | login -u "$DOCKERUSER" --password-stdin
  
  # push the images to dockerhub
  - docker push kothamsu/multi-client
  - docker push kothamasu/multi-nginx
  - docker push kothamasu/multi-server
  - docker push kothamasu/multi-worker
  
