sudo: required
services: 
  - docker
  
before_install:
  - docker build -t kothamasu/docker-complexreact -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kothamasu/docker-complexreact npm run test

after_success:
  - docker build -t kothamasu/multi-client ./client
  - docker build -t kothamasu/multi-nginx ./nginx
  - docker build -t kothamasu/multi-server ./server
  - docker build -t kothamasu/multi-worker ./worker

  # login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # push the images to dockerhub
  - docker push kothamasu/multi-client
  - docker push kothamasu/multi-nginx
  - docker push kothamasu/multi-server
  - docker push kothamasu/multi-worker
  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "MultiDocker-env"
  env: "MultidockerEnv-env"
  bucket_name: "elasticbeanstalk-us-east-2-873302939557"
  bucket_path: "MultiDocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
